name: Jupyter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main", "logo"]
  # pull_request:
  # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  R-CMD-check:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - id: Python_pip
        name: Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pip"
      - run: pip install -r requirements.txt

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: any::rcmdcheck
      #     needs: check

      # - uses: r-lib/actions/check-r-package@v2

      # - id: R-kernel
      #   name: R-kernel
      #   uses: r-lib/actions/setup-r@v2

      - run: Rscript r_files/dep.r
      # This workflow contains a single job called "build"
      # build:
      #   # The type of runner that the job will run on
      #   runs-on: windows-2022

      #   # Steps represent a sequence of tasks that will be executed as part of the job
      #   steps:
      #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #     - id: repo
      #       name: Repo Checks-out
      # uses: actions/checkout@v3

      - id: R_book
        name: Rbuild
        # run: jupyter execute 01_r-notebook-linear-model-overfiting.ipynb
        # run: jb clean -a . ; jb build .
        run: jb build .
        shell: bash

      - id: ghp
        name: none
        run: ghp-import -n -p -f _build/html
        shell: bash

      - id: commit
        name: Commit files
        run: git config --local user.name action-user

          git config --local user.email "actions@github.com"

          git add -A

          git commit -m "update files"

          git push origin logo

        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}

          username: github-actions
